ALTER SESSION SET NLS_DATE_FORMAT ='YYYY/MM/DD HH24:MI';
select USERNAME, ACCOUNT_STATUS, PROFILE, DEFAULT_TABLESPACE DEF_TBS, TEMPORARY_TABLESPACE TMP_TBS, CREATED, PASSWORD_VERSIONS from dba_users order by created;
exit
